version: '3'

services:
  # Python
  python:
    container_name: python
    build:
      context: ./docker/py
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./docker/py/test:/var/www/html
    ports:
      - "8089:8089"
#    network_mode: "sample-network5"

#networks:
#  sample-network5: